### ISSUE TITLE
How do I configure http_in_count?

### ISSUE THREAD

**Issue by martonsz** [inspectIT/inspectit-ocelot#1175]
I am getting thousands of individual metrics for `http_in_count` because our API is using the path as an argument.

Can I disable the path using regex?
Can I disable all `http_*_count` entries?

It looks like this.
```
http_in_count{environment="production",http_method="DELETE",http_path="/foo.bar/arg1,...}
http_in_count{environment="production",http_method="DELETE",http_path="/foo.bar/arg2,...}
http_in_count{environment="production",http_method="DELETE",http_path="/foo.bar/arg3,...}
... thousands of lines
http_in_count{environment="production",http_method="DELETE",http_path="/foo.bar/argN,...}
```

I am using the prometheus exporter
jmx_prometheus_javaagent 1.11.1

**Comment by mariusoe** [comment]
Hi @martonsz 

you don't have to disable the `http_*_count` metric because you could use a path parametrization rule to "remove" those dynamic parts of the HTTP path. Thus, you still have information about the related endpoint.

This part is currently missing in the documentation, but I put this on our list to add to the documentation.

You can find an example in the following file of the agent's default configuration: [http-path-parametrization.yml](https://github.com/inspectIT/inspectit-ocelot/blob/2de492186058d216dac26b857d1512e0069078e3/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/http/_shared/http-path-parametrization.yml)

By default, the agent contains a rule named `r_http_parametrize_path`. In this rule, you can include custom rules to modify the `http_path` used by the metric recording rules. Doing this, you can prevent a metric explosion due to a dynamic part (e.g. the argument in your case).

Just create a custom rule, which generates a content-variable `http_path` based on the value of a existing one with the same name. In your case, you can use an action which uses regex to remove the dynamic part - like this:
```
'r_your_custom_rule':
  entry:
    'http_path':
      action: 'a_regex_replaceAll_multi'
      data-input:
        string: 'http_path'
      constant-input:
        'patterns_and_replacements':
          - pattern:      '\/foo.bar\/[^/]+'
            replacement:  '/foo.bar/{argument}'
```

Doing this, e.g.`/foo.bar/arg1...` will transformed into `/foo.bar/{argument}`.

Then, include this new rule into the predefined `r_http_parametrize_path` rule.
```
'r_http_parametrize_path':
  include:
    'r_your_custom_rule': true 
```

Now, you don't have thousands of individual metric, but just a single one, representing your endpoint.

**Comment by martonsz** [comment]
Thank you! It helped.

I "disabled" this for now and will pick it up when I have more time to go through all the API calls. And learn how custom rules works.

This is what I did to reduce the amount of metrics for now:

```yaml
'r_your_custom_rule':
        entry:
          'http_path':
            action: 'a_regex_replaceAll_multi'
            data-input:
              string: 'http_path'
            constant-input:
              'patterns_and_replacements':
                - pattern:      '\/.*'
                  replacement:  '/{http_path_todo}'
```
