### ISSUE TITLE
Wrong metrics referral causes inspectit not to expose any metric on prometheus metrics endpoint

### ISSUE THREAD

**Issue by albersma69** [inspectIT/inspectit-ocelot#1233]
The following example contains an error when refering to the metrics "pets". It references the view "pets/count" instead of the metric "pets" itself. 

```
inspectit:
  metrics:
    definitions:
      '[pets]':
        type: LONG
        unit: count
        description: "The number of saves per pet type"
        views:
          '[pets/count]':
            aggregation: COUNT
            tags:
              pet_type : true
  instrumentation:
    scopes:
      's_save_pet':
        type: 
          name: 'org.springframework.samples.petclinic.customers.web.PetService'
        methods:
          - name: save
            matcher-mode: EQUALS_FULLY
    rules:
      'r_extract_pet_type':
        scopes:
          's_save_pet': true
        metrics:
          '[pets/count]':
            value: 1
            data-tags:
              pet_type: 'extract-pet-type'
        exit:
          extract-pet-type:
            action: 'a_extract_pet_type_from_save'

```

This leads to the following error message during startup of the instrumented java app:
`
021-11-17 12:41:54,155 ERROR 8635   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   : Error loading the configuration 'inspectit'.
2021-11-17 12:41:54,156 ERROR 8636   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   : instrumentation.rules.r_extract_pet_type.metrics => Metric 'pets/count' is not defined in inspectit.metrics.definitions!
2021-11-17 12:41:54,191 ERROR 8671   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   : Startup configuration is not valid! Using fallback configuration but listening for configuration updates...
`

Furthermore, the prometheus endpoint is dead, ie. not available. 
I'd expect that the this wrong config should be skipped and inspectIT would go on with the remaining instrumentation and keep surving the /metrics port. Even the default port 8888 is not served at all.
