### ISSUE TITLE
[Feature] - Enable Lambda expressions in actions

### ISSUE THREAD

**Issue by EddeCCC** [inspectIT/inspectit-ocelot#1691]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to use Java code snippets, which contain lambda expressions for actions. This is probably the fault of Javassist, which is responsible to compile the code snippets. Since more and more libraries we want to instrument use asynchronous approaches, we need to be able to work with lambdas.

**Describe the solution you'd like**
Check, if Javassist is capable of using lambdas in code snippets. Maybe we would have to look for another library.

**Additional context**
I discoverd the OpenTelemetry Java agent sometimes uses the decorator pattern, to add instrumentation logic to callback functions. For example here: [DecoratorFunctions](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/reactor/reactor-netty/reactor-netty-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/reactornetty/v1_0/DecoratorFunctions.java#L49).

It would be awesome, if we could use actions like this:

```
a_decorate:
  is-void: true
  input:
    _arg0: java.util.function.BiConsumer
    _context: InspectitContext
  value-body: |
    BiConsumer callback = _arg0;
    BiConsumer wrapper = (k,v) -> {
      // insert instrumentation logic
      String key = (String) k;
      _context.setData("my-key", key);
      // call original function
      callback.accept(k,v);
    };
    _arg0 = wrapper;
```

**Comment by EddeCCC** [comment]
As our documentation says: 

> Under the hood, inspectIT uses the [javassist](http://www.javassist.org/) library, where all imposed restrictions can be found. The most important ones are that neither Autoboxing, Generics, Anonymous Classes or Lambda Expressions are supported.

**Comment by EddeCCC** [comment]
I couldn't find any tool to replace Javassist and allow lambda or anonymous classes within actions.

## Alternative approach
Another approach would be to outsource the logic containing lambdas into an internal InspectIT class. Such class could be used similarly like `InspectitContext` or `ObjectAttachments` to wrap instrumentation logic around another functional interface.
The action could look something like this:
```yaml
a_wrapper:
  is-void: true
  imports:
    - java.util.function
  input:
    _arg0: BiConsumer
    _wrapper: InspectitWrapper
  value-body: |
    BiConsumer callback = _arg0;
    // This is just a general example. We could define more precise methods for tracing or metrics
    BiConsumer wrapper = _wrapper.wrap(callback); 
    _arg0 = wrapper;
```
This approach was tested in the mentioned draft.

## Overwriting Java objects
However, at the moment the line `_arg0 = wrapper` is not working as intended. The instrumented method will not use the overwritten value for `_arg0` but continue to use the original value after the action. Thus, there is still some logic missing, which allows InspectIT to overwrite objects and also pass the new value to the instrumented method. 

ByteBuddy allows to overwrite objects like arguments when using `readOnly=false`, but the reassignment has to happen inside the `@Advice` itself. This approach was also tested in the mentioned draft.
I am unsure, if we can overwrite objects besides method arguments (for instance context data) similarly.

For me it is also unclear if we actually want to allow users to overwrite Java objects entirely due to security concerns...
