### ISSUE TITLE
Improve Flexibility of Metric Outputs

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#440]
Currently, metrics outputs are defined as follows:
```
metrics:
  '[my/metric]' : my_value
```
This limits the user in the following ways:
* Only one output per metric is possible (e.g. writing to values to the same metric is not possible)
* Conditions can not be defined
* Tags have to be setup using data in the inspectit context

To overcome this limitations we can offer an "expert" way of configuring metric outputs:
```
metrics:
  first_metric_definition : 
    value: my_value
    metric: "my/metric"
    constant-tags:
      protocoll: "http"
    data-tags:
      receiver: some_receiver_data
    conditions:
      only-if-true: ...
```
The key is to allow both ways of configuring metrics to keep the configuration simple.
This means that the first example shown effectively is a "shortcut" for the following definition:
```
metrics:
  '[my/metric]' : 
     value: my_value
```
This can be realized registering a specialized ConversionService which converts the simple string to the desired "default" output configuration.

**Comment by mariusoe** [comment]
We should keep the configuration simple, thus, only using the "advanced" approach for defining metrics. In the same step, the tag assignment should always be explicitly done via the example above:

```
constant-tags:
      protocoll: "http"
    data-tags:
      receiver: some_receiver_data
```

This way, the data flag `is-tag` will be obsolete and can be removed. Removing the implicit connection of "data elements" which are flagged as an tag (`is-tag`) will reduce complecity of the configuration. A configuration which is less complex should be more user-friendly for the end users than a shortcut for the metric definition.

This will lead to a breaking change of the configuration and should be done early.
