### ISSUE TITLE
Allow rules to include each other

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#457]
At the moment it is not possible to express dependencies between multiple rules.
This can lead to a suboptimal instrumentation where the same work is done multiple times.

For example, assume that there are two rules: `http_servlet_metrics` and `http_servlet_tracing`.
Both require the `http_path` to be extracted from the request. Therefore both rules add an action call performing this task.
If now both rules are enabled, the work will be done twice.

This can be avoided by adding an inclusion mechanism to rules, allowing to extract common actions:

```
rules:
  http_servlet_tracing:
    includes:
      http_servlet_extract_data: true
    ...
  http_servlet_tracing:
    includes:
      http_servlet_extract_data: true
    ...
  http_servlet_extract_data:
    entry:
      http_path: ...
    ...
```
Inclusion results in all actions (and tracing settings) to be applied from the included rules.
So A includes B can be read as "For each method which is instrumented with rule A, also apply rule B".

How does this help us? We can now ensure that each rule is only applied once.
This means it does not matter if you enable only metrics, only tracing or both: the data extraction happens only exactly once.

This can then further be used to optimize existing rules, for example to make sure that the method duration is only measured once.
