### ISSUE TITLE
Allow scopes to exclude certain methods / classes

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#525]
Scopes allow to select specific methods from classes ast the moment.
E.g. it is easily possible to define scope for all classes implementing a certain interface.

It is however very difficult to exclude certain methods / classes at the moment. For example if you want to instrument all classes implementing an interface except for one class.

To solve this, we should add an `exclude` option to scopes:
```
inspectit:
  instrumentation:
    scopes:
       scope_a:
         ...
       scope_b:
         exclude:
           scope_a: true
         ...
```
In this example scope_b would *not* instrument the methods matched by scope_a.

It is important that the configuration validation ensures that there are no cycles in the exclude-definitions.
