### ISSUE TITLE
EUM server stops beacon processing when the regex beacon processor fails

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#638]
If the EUM server configuration defines a derived beacon attributeswhich is not correct, e.g. wrong group index in the replacement string, the processing stops. In case this attribute is at the beginning or in the middle of multiple extra beacon attributes, the remaining attributes which haven't been proccessed will be skipped.

Example:
```
PGU_PORT:
        input: pgu
        regex: "^.*\\/\\/([^:\\/]*):(\\d+).*$"
        replacement: "$2"
BROKEN:
        input: u
        regex: ".*"
        replacement: "$1"
PGU_PATH:
        input: pgu
        regex: "^.*\\/\\/([^\\/]*)([^?]*).*$"
        replacement: "$2"
```

In this example, only the `PGU_PORT` will be available because the proccessing stop at the `BROKEN` attribute and prevents the processing of the `PGU_PATH`
