### ISSUE TITLE
Missing documentation: Specifing arrays as constant-inputs does not work

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#650]
It is possible to define (multi-dimensional) arrays as input for actions:
```
actions:
  my_action:
    input:
      values: int[]
```
As long as the type is known, it should be possible to provide the value for this input as a constant:

```
rules:
  my_rule:
    entry:
      my_data:
        action: my_action
        constant-input:
          values: [1,2,3,4]
```

However, at the moment the Agent rejects the configuration with the following error message:
```
instrumentation.rules.my_rule.entry.my_data=> The input 'values' of 'my_action' cannot be specified as a non-null constant value, as it has the unknown type 'int[]'
```

The root cause for this issue is `rocks.inspectit.ocelot.config.utils.ConfigUtils.locateTypeWithinImports`, which does not support the `[]` arrays syntax. This needs to be extended in order to support arrays.
