### ISSUE TITLE
I can't get any trace from service.

### ISSUE THREAD

**Issue by GuazP** [inspectIT/inspectit-ocelot#720]
There are logs when i tried to setup agent and export any traces to jaeger.
[agent.log](https://github.com/inspectIT/inspectit-ocelot/files/4581092/agent.log)
[exceptions.log](https://github.com/inspectIT/inspectit-ocelot/files/4581093/exceptions.log)
There is no error, maybe something other I am doing wrong? 

There is instrumentation provided to ocelot-config-server:
```
inspectit:
  metrics: {frequency: 1s}
  logging: {debug: false}
  instrumentation:
    rules:
      example_rule:
        tracing: {start-span: true, store-span: my_span_data, end-span: false}
      record_method_duration:
        entry:
          method_entry_time: {action: timestamp_nanos}
          method_name: {action: get_method_fqn}
        exit:
          method_duration:
            action: elapsed_millis
            data-input: {sinceNanos: method_entry_time}
        metrics: {'[method/duration]': method_duration}
    scopes:
      example-scope:
        superclass: {name: java.lang.Object, matcher-mode: CONTAINS}
        advanced: {instrument-only-inherited-methods: false, disable-safety-mechanisms: true}
  exporters:
    tracing:
      jaeger: {enabled: true, url: 'http://jaeger:14628/api/traces', service-name: '${inspectit.service-name}'}
```
Someone see something wrong in this?

I would be gratefull if someone can tell where I did a mistake or where I should look :)

**Comment by JonasKunz** [comment]
You have defined rules and scopes, but did not assign any scopes to your rules.

In addition, you should *not* use the `example-scope` you provided:
You would instrument all methods (e.g. including java.lang ones) which guaranteed to kill your JVM.

A minimal configuration for tracing custom methods looks like the following:

```
inspectit:
  instrumentation:
    rules:
      example_rule:
        scopes:
          your_scope: true #here we say that this rule should be applied to all methods matching "your_scope"
        tracing:
          start-span: true
    scopes:
      your_scope:
        #scope definition here, e.g. all public methods from a package....
```
