### ISSUE TITLE
HttpUrlConnection can propagate wrong spanID

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#743]
Due to a bug in the default configuration it is possible that two spans are started for the same HTTPUrlConnection object, where only the second span will be ended.
In addition, only the span id of the span who is never ended is sent, causing an invalid span ID to be propagated.

The issue can be fixed by adding the following configuration:
```
inspectit:
  instrumentation:
    'r_httpurlconnection_tracing_start':
      post-entry:
        'span_obj':
          only-if-true: 'httpurlconnection_is_start'
```
