### ISSUE TITLE
Can't filter a specific JMX metric using `object-names`

### ISSUE THREAD

**Issue by martonsz** [inspectIT/inspectit-ocelot#767]
# Can't filter a specific JMX metric using `object-names`

I am trying to use  `object-names` to select only the jmx metrics that I need. In this example I am trying to only get  `maxthreads` from  `Catalina:type=Executor,name=tomcatThreadPool`. But I only manage to filter other metrics.

# Info

Running as agent
Version 1.3

Tomcat version: 9.0.34
Java: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)

I am making a full restart between my tests. Because changing `object-names` dynamically only registers when I add a new key. Nothing happens when I remove a key. But that is another issue. I am using file based configuration.

```
...ocelot.core.AgentImpl    : Starting inspectIT Ocelot Agent...
...ocelot.core.AgentImpl    :       Version: 1.3
...ocelot.core.AgentImpl    :       Build Date: Thu May 07 13:59:13 UTC 2020
...ocelot.core.AgentImpl    : OpenCensus was loaded in bootstrap classloader
...ocelot.core.config.InspectitEnvironment   : initializing file based configuration from dir: /inspectit-config
...Command line argument: -javaagent:/usr/local/inspectit-ocelot-agent.jar

java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

## Config 1, empty object-names

If I don't set `object-names` I get all of the jmx metrics. This is just to see if the metric exists.

```yaml
---
inspectit:
  service-name: ORIGO
  ...
  exporters.metrics.prometheus:
    enabled: true
    port: 8081
  metrics:
    jmx:
      enabled: true
      lower-case-metric-name: true
      #object-names:
      #  '[Catalina:type=Executor]': true
```

Result: 983 rows starting with `jvm_jmx_`
The one I am interested in is there ->  `jvm_jmx_catalina_executor_maxthreads`. But I only want this metric. And not 982 others.

```shell
curl -s localhost:8081 | grep "^jvm_jmx_" | wc -l
983

curl -s localhost:8081 | grep "maxthreads"
# HELP jvm_jmx_catalina_executor_maxthreads last value of Maximum number of allocated threads [na]
# TYPE jvm_jmx_catalina_executor_maxthreads gauge
jvm_jmx_catalina_executor_maxthreads{environment="development",host="tomcat-origo-a-656b879756-hz6wb",host_address="10.42.0.209",name="tomcatThreadPool",service="ORIGO",} 200.0
```

## Config 2, type=Executor

If I set `'[Catalina:type=Executor]': true` then I don't get any jmx metrics.

```yaml
---
inspectit:
  ...
  metrics:
    jmx:
      enabled: true
      lower-case-metric-name: true
      object-names:
        '[Catalina:type=Executor]': true
```

Result: 0 rows starting with `jvm_jmx_`

```shell
curl -s localhost:8081 | grep "^jvm_jmx_" | wc -l
0

curl -s localhost:8081 | grep "maxthreads"
# empty
```
## Config 3, type=Engine

If I set `'[Catalina:type=Engine]': true` I get all the available metrics for this type. Which is in the same domain: "Catalina". Why doesn't it work when I use `Catalina:type=Executor`?
*Bonus question: How do I limit to only one of these rows? I have tried* `'[Catalina:type=Engine,name=backgroundProcessorDelay]': true`. *But then I get 0 results again.*

```yaml
---
inspectit:
  ...
  metrics:
    jmx:
      enabled: true
      lower-case-metric-name: true
      object-names:
        '[Catalina:type=Engine]': true
```

Result: 3 rows starting with `jvm_jmx_catalina_engine_`

```shell
curl -s localhost:8081 | grep "^jvm_jmx_" | wc -l
3

# Grep all jvm_jmx_ rows.
curl -s localhost:8081 | grep "^jvm_jmx_"
jvm_jmx_catalina_engine_backgroundprocessordelay{environment="development",host="tomcat-origo-a-656b879756-9px5v",host_address="10.42.0.208",service="ORIGO",} 10.0
jvm_jmx_catalina_engine_startchildren{environment="development",host="tomcat-origo-a-656b879756-9px5v",host_address="10.42.0.208",service="ORIGO",} 1.0
jvm_jmx_catalina_engine_startstopthreads{environment="development",host="tomcat-origo-a-656b879756-9px5v",host_address="10.42.0.208",service="ORIGO",} 1.0
```

I have a screen shoot of this bean from VisualVM: https://snipboard.io/Na5BKe.jpg 

![Image of Yaktocat](https://snipboard.io/Na5BKe.jpg)
