### ISSUE TITLE
Extend the auto-completion endpoint to provide auto-completion suggestions for metrics

### ISSUE THREAD

**Issue by mbrill-nt** [inspectIT/inspectit-ocelot#785]
Currently the autocompleter does not autocomplete metrics. An autocompleter should be added which suggests key words for the metrics section.

**Comment by mariusoe** [comment]
Especially, for metric attributes in a rule block.

Example:
```
inspectit:
  instrumentation:
    rules:
      'r_test':
        metrics:
          'my_metric':
            ...
            <missing autocompletion>
```
